Repository AY2021S1-TIC4001-2/tp, pull requests merged in 2020-10, with the labels that each got.

#27 Add List round 1
  src/main/java/moneytracker/command/AddExpenseCommand.java
  src/main/java/moneytracker/command/ListCommand.java
  src/main/java/moneytracker/transaction/TransactionList.java
  src/main/java/moneytracker/ui/Ui.java
Labels: type.Task

#44 Branch list two by type
  src/main/java/moneytracker/MoneyTracker.java
  src/main/java/moneytracker/command/ListCommand.java
  src/main/java/moneytracker/transaction/Transaction.java
  src/main/java/moneytracker/transaction/TransactionList.java
  src/main/java/moneytracker/ui/Ui.java
  src/test/java/moneytracker/transaction/TransactionTest.java
Labels: type.Task

#49 Add user guide one
  docs/UserGuide.md
  src/main/java/moneytracker/ui/Ui.java
Labels: type.Story, type.Task

#56 Add checking mechanism to add expense and add income commands
  src/main/java/moneytracker/command/AddExpenseCommand.java
  src/main/java/moneytracker/command/AddIncomeCommand.java
  src/main/java/moneytracker/storage/Storage.java
  src/main/java/moneytracker/transaction/CategoryList.java
  src/main/java/moneytracker/transaction/TransactionList.java
Labels: priority.High, type.Task
